# .github/actions/common-action-1/action.yaml
name: "common1"
description: "common method 1"
inputs:
  name:
    required: true
    description: "Hello action"
runs:
  using: "composite"
  steps:
    - run: |
        echo "Hello, ${{ inputs.name }}!"
        
        # echo "test2=hello world" >> "$GITHUB_OUTPUT"
        touch "mv-test.txt"
        echo "pwd:: "
        pwd        
        ls
        echo "${GITHUB_OUTPUT}"
        cat "${GITHUB_OUTPUT}"
        echo "test1=hello" >> "$GITHUB_OUTPUT"
      shell: bash
