# .github/actions/common-action-2.yml
name: "common2"
description: "common method 2"
inputs:
  name:
    required: true
    description: "Bye action"
runs:
  using: "composite"
  steps:
    - run: echo "Bye, ${{ inputs.name }}!"
