# .github/actions/common-action-2/action.yaml
name: "common2"
description: "common method 2"
inputs:
  name:
    required: true
    description: "Bye action"
runs:
  using: "composite"
  steps:
    - run: |
        echo "Bye, ${{ inputs.name }}!"
        echo "Test1: ${test1}"
        echo "Test2: ${test2}"
        echo "pwd:: "
        pwd       
        ls
        echo "Finish of pipeline."
        env
        exit 0
      shell: bash
