name: Sample CI

on:
  pull_request:
    branches:
      - development
      - master
      - releases*

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Run pre-commit hooks & Type check
      id: code-checks
      run: |
        echo "in code-checks"
    - name:  Run Unit tests
      id: unit-tests
      run: |
        echo "in unit-tests"
    - name: Build Application container
      id: build-container
      run: |
        echo "in build application container"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: code-checks
    strategy:
      matrix:
        values: ['e2e-1', 'e2e-2', 'e2e-3', 'e2e-4']
    steps:
      - name: E2E Tests - ${{matrix.values}}
        run: |
          value="${{matrix.values}}"
          echo "value:: ${value}"

  # push-dev-registry:
  #   runs-on: ubuntu-latest
  #   if: github.base_ref == 'development'
  #   needs: e2e-tests
  #   steps:      
  #   # - uses: actions/checkout@v4
  #   - name: Build Feature Environment
  #     env:
  #       GITHUB_CONTEXT: ${{ toJson(github) }}    
  #     run: |
  #       echo "in push dev registry"
  #       echo "$GITHUB_CONTEXT"        

  push-non-dev-registry:
    runs-on: ubuntu-latest
    if: github.base_ref != 'development' && !startsWith(github.base_ref, 'release')
    needs: e2e-tests
    steps:      
    # - uses: actions/checkout@v4
    - name: Build Feature Environment
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}    
      run: |
        echo "in non dev registry"
        echo "$GITHUB_CONTEXT"        

  push-prod-registry:
    runs-on: ubuntu-latest
    if: startsWith(github.base_ref, 'release')
    needs: e2e-tests
    steps:      
    # - uses: actions/checkout@v4
    - name: Build Feature Environment
      run: |
        echo "in prod registry"


  build-feat-env:
    runs-on: ubuntu-latest
    needs: push-non-dev-registry
    if: startsWith(github.base_ref, 'development')
    steps:      
    # - uses: actions/checkout@v4
    - name: Build Feature Environment
      run: |
        echo "build feature environment based on script"
        ./scripts/is_feature_app.sh

  code-engine-deploy:
    runs-on: ubuntu-latest
    needs: push-dev-registry
    if: github.base_ref == 'development'
    steps:      
    - uses: actions/checkout@v4
    - name: Build Feature Environment
      run: |
        echo "code engine deploy based on checks in script"
