name: Sample CI

on:
  pull_request:
    branches:
      - development
      - master
      - releases*

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Run pre-commit hooks & Type check
      id: code-checks
      run: |
        echo "in code-checks"
    - name:  Run Unit tests
      id: unit-tests
      run: |
        echo "in unit-tests"
    - name: Build Application container
      id: build-container
      run: |
        echo "in build application container"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: code-checks
    steps:
      - uses: actions/checkout@v4
      - name: E2E Tests
        with:
          bucket: 'bucket-value'
        uses: ./.github/actions/e2e-tests   

  push-non-dev-registry:
    runs-on: ubuntu-latest
    if: github.base_ref == 'development' || startsWith(github.base_ref, 'release')
    needs: e2e-tests
    steps:      
    # - uses: actions/checkout@v4
    - name: Build Feature Environment
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}    
      run: |
        echo "in non dev registry"
        echo "$GITHUB_CONTEXT"        

  build-feat-env:
    runs-on: ubuntu-latest
    needs: push-non-dev-registry
    if: startsWith(github.base_ref, 'development')
    steps:      
    - uses: actions/checkout@v4
    - name: Build Feature Environment
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        MY_TOKEN: ${{ secrets.MY_REPO_SECRET }}    
      run: |
        echo "build feature environment based on script"
        echo "----"
        pwd
        echo "-----"
        ls
        echo "-----"
        ./scripts/is_feature_app.sh
