# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci

env:
  MY_SECRET: ${{ secrets.MY_GITHUB_TOKEN }}
  

on:
  # push:
  #   branches: ['master', 'release-*', 'development', 'bugfix/*', 'feat/*']
  pull_request:
    branches: ['master', 'release-*', 'development', 'main']
jobs:

  hello-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: hello
      id: hello
      run: |
        echo "hello"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        echo "${GITHUB_PATH}"
        echo "GITHUB_ACTION: ${GITHUB_ACTION}"
        echo "${GITHUB_RUN_NUMBER}"
        echo "${RUNNER_NAME}"
        echo "GITHUB_REPOSITORY_OWNER_ID: ${GITHUB_REPOSITORY_OWNER_ID}"
        echo "${GITHUB_TRIGGERING_ACTOR}"
        echo "${GITHUB_REF_TYPE}"
        echo "${GITHUB_REPOSITORY_ID}"
        echo "GITHUB_SHA: ${GITHUB_SHA}"
        echo "${GITHUB_WORKFLOW_REF}"
        echo "${GITHUB_REF}"
        echo "GITHUB_API_URL: ${GITHUB_API_URL}"
        echo "${GITHUB_EVENT_PATH}"
        echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
        echo "${GITHUB_STEP_SUMMARY}"
        echo "${GITHUB_ACTOR}"
        echo "GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"
        echo "${GITHUB_WORKFLOW_SHA}"
        echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
        echo "${GITHUB_JOB}"
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
        echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
        echo "GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}"
        echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
        echo "${GITHUB_ACTION_REF}"
        echo "GITHUB_OUTPUT: ${GITHUB_OUTPUT}"
        echo "-----"

        cat "${GITHUB_EVENT_PATH}"
        echo "-----"

        ./scripts/gh-actions/is_open_pull_request.sh
        echo "-----"
        env

  # pre-commit:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Run pre-commit hooks & Type check
  #     id: 'pre-commit'
  #     run: |
  #       echo "Run pre-commit hooks & Type check"

  # unit-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Run Unit tests
  #     id: 'run-unit-tests'
  #     run: |
  #       echo "Run Unit tests"
  # build-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build Application container
  #     id: 'build-container-image'
  #     run: |
  #       echo "Build Application container"

  # e2e-1:
  #   runs-on: ubuntu-latest
  #   needs: ['pre-commit', 'unit-tests', 'build-image']
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: e2e - bucket 1
  #     id: 'e2e-bucket-1'
  #     run: |
  #       echo "e2e - bucket 1"

  # e2e-2:
  #   runs-on: ubuntu-latest
  #   needs: ['pre-commit', 'unit-tests', 'build-image']
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: e2e - bucket 2
  #     id: 'e2e-bucket-2'
  #     run: |
  #       echo "e2e - bucket 2"

  # e2e-3:
  #   runs-on: ubuntu-latest
  #   needs: ['pre-commit', 'unit-tests', 'build-image']
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: e2e - bucket 3
  #     id: 'e2e-bucket-3'
  #     run: |
  #       echo "e2e - bucket 3"

  # e2e-4:
  #   runs-on: ubuntu-latest
  #   needs: ['pre-commit', 'unit-tests', 'build-image']
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: e2e - bucket 4
  #     id: 'e2e-bucket-4'
  #     run: |
  #       echo "e2e - bucket 4"

  # push-dev:
  #   runs-on: ubuntu-latest
  #   needs: [e2e-1, e2e-2, e2e-3, e2e-4]
  #   if: github.base_ref == 'main'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: 'push image to registry for main'
  #       run: |
  #         echo "push image to registry - main"

  # push-release:
  #   runs-on: ubuntu-latest
  #   needs: [e2e-1, e2e-2, e2e-3, e2e-4]
  #   if: github.base_ref == 'release'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: 'push img for release'
  #       run: |
  #         echo "push image to registry - release"

  # build-dev:
  #   runs-on: ubuntu-latest
  #   needs: push-dev
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: 'build feat env'
  #       run: |
  #         echo "build feat environment"

  # build-release:
  #   runs-on: ubuntu-latest
  #   needs: push-release
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: 'build feat env - release'
  #       run: |
  #         echo "build feat environment - release"          